version: '3'

services:
#  web:
#    build: .
#    ports:
#      - "8000:80"
#    depends_on:
#      - db
   db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql/data
volumes:
  db_data:
#  wp_data:
