version: '3'

services:
#  web:
#    build: .
#    ports:
#      - "8000:80"
#    depends_on:
#      - mssql
#   mssql:
#    image: mcr.microsoft.com/mssql/server:2017-latest
#    environment:
#      - SA_PASSWORD=P@ssw0rd
#      - ACCEPT_EULA=Y
#    ports:
#      - "1433:1433"
#    volumes:
#      - mssql_data:/var/opt/mssql/data
   mongo:
     image: mongo
     restart: always
     environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd
     ports:
       - "27017:27017"
     volumes:
       - mongo_data:/data/db
   mqtt:
     image: eclipse-mosquitto
     ports:
       - "1883:1883"
       - "9001:9001"
     volumes:
       - mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
#  mssql_data:
  mongo_data:
